version: '3'

services:      
  iss-pricing-service:
    container_name: iss-pricing-service
    image: iss-pricing-service
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=test    
      - POSTGRES_HOST=postgres_db      
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_PORT=5432      
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db

  postgres_db:
    image: "postgres:9.6-alpine"
    container_name: postgres_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_HOST=postgres_db      
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
 
volumes:
  postgres-data: